site_name: Django REST framework
site_url: http://www.django-rest-framework.org/
site_description: Django REST framework - Web APIs for Django

repo_url: https://github.com/tomchristie/django-rest-framework

theme_dir: docs_theme

pages:
 - ['index.md', 'Home']
 - ['tutorial/quickstart.md', 'Tutorial', 'Quickstart']
 - ['tutorial/1-serialization.md', 'Tutorial', '1 - Serialization']
 - ['tutorial/2-requests-and-responses.md', 'Tutorial', '2 - Requests and responses']
 - ['tutorial/3-class-based-views.md', 'Tutorial', '3 - Class based views']
 - ['tutorial/4-authentication-and-permissions.md', 'Tutorial', '4 - Authentication and permissions']
 - ['tutorial/5-relationships-and-hyperlinked-apis.md', 'Tutorial', '5 - Relationships and hyperlinked APIs']
 - ['tutorial/6-viewsets-and-routers.md', 'Tutorial', '6 - Viewsets and routers']
 - ['api-guide/requests.md', 'API Guide', 'Requests']
 - ['api-guide/responses.md', 'API Guide', 'Responses']
 - ['api-guide/views.md', 'API Guide', 'Views']
 - ['api-guide/generic-views.md', 'API Guide', 'Generic views']
 - ['api-guide/viewsets.md', 'API Guide', 'Viewsets']
 - ['api-guide/routers.md', 'API Guide', 'Routers']
 - ['api-guide/parsers.md', 'API Guide', 'Parsers']
 - ['api-guide/renderers.md', 'API Guide', 'Renderers']
 - ['api-guide/serializers.md', 'API Guide', 'Serializers']
 - ['api-guide/fields.md', 'API Guide', 'Serializer fields']
 - ['api-guide/relations.md', 'API Guide', 'Serializer relations']
 - ['api-guide/validators.md', 'API Guide', 'Validators']
 - ['api-guide/authentication.md', 'API Guide', 'Authentication']
 - ['api-guide/permissions.md', 'API Guide', 'Permissions']
 - ['api-guide/throttling.md', 'API Guide', 'Throttling']
 - ['api-guide/filtering.md', 'API Guide', 'Filtering']
 - ['api-guide/pagination.md', 'API Guide', 'Pagination']
 - ['api-guide/versioning.md', 'API Guide', 'Versioning']
 - ['api-guide/content-negotiation.md', 'API Guide', 'Content negotiation']
 - ['api-guide/metadata.md', 'API Guide', 'Metadata']
 - ['api-guide/format-suffixes.md', 'API Guide', 'Format suffixes']
 - ['api-guide/reverse.md', 'API Guide', 'Returning URLs']
 - ['api-guide/exceptions.md', 'API Guide', 'Exceptions']
 - ['api-guide/status-codes.md', 'API Guide', 'Status codes']
 - ['api-guide/testing.md', 'API Guide', 'Testing']
 - ['api-guide/settings.md', 'API Guide', 'Settings']
 - ['topics/documenting-your-api.md', 'Topics', 'Documenting your API']
 - ['topics/internationalization.md', 'Topics', 'Internationalization']
 - ['topics/ajax-csrf-cors.md', 'Topics', 'AJAX, CSRF & CORS']
 - ['topics/browser-enhancements.md', 'Topics',]
 - ['topics/browsable-api.md', 'Topics', 'The Browsable API']
 - ['topics/rest-hypermedia-hateoas.md', 'Topics', 'REST, Hypermedia & HATEOAS']
 - ['topics/third-party-resources.md', 'Topics', 'Third Party Resources']
 - ['topics/contributing.md', 'Topics', 'Contributing to REST framework']
 - ['topics/project-management.md', 'Topics', 'Project management']
 - ['topics/rest-framework-2-announcement.md', 'Topics', '2.0 Announcement']
 - ['topics/2.2-announcement.md', 'Topics', '2.2 Announcement']
 - ['topics/2.3-announcement.md', 'Topics', '2.3 Announcement']
 - ['topics/2.4-announcement.md', 'Topics', '2.4 Announcement']
 - ['topics/3.0-announcement.md', 'Topics', '3.0 Announcement']
 - ['topics/kickstarter-announcement.md', 'Topics', 'Kickstarter Announcement']
 - ['topics/release-notes.md', 'Topics', 'Release Notes']
 - ['topics/credits.md', 'Topics', 'Credits']
